### ISSUE TITLE
go test panic

### ISSUE THREAD

**Issue by rfyiamcool** [smallnest/gosercomp#13]
## path

- go 1.14
- mac os

```
go version go1.14.6 darwin/amd64
```

## shell

```
go test -bench=.
```

## return

```
panic: field model.GogoProtoColorGroup.id has invalid type: got int32, want pointer

goroutine 87 [running]:
google.golang.org/protobuf/internal/impl.fieldInfoForScalar(0x19859c0, 0xc000172840, 0x1725383, 0x2, 0x0, 0x0, 0x1985ae0, 0x174c3e0, 0x1725387, 0x29, ...)
	/Users/ruifengyun/go/pkg/mod/google.golang.org/protobuf@v1.25.0/internal/impl/message_reflect_field.go:228 +0x800
google.golang.org/protobuf/internal/impl.(*MessageInfo).makeKnownFieldsFunc(0xc00015c000, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xc0002a8630, 0xc0002a8660, 0xc0002a8690, 0xc0002a86c0)
	/Users/ruifengyun/go/pkg/mod/google.golang.org/protobuf@v1.25.0/internal/impl/message_reflect.go:67 +0x938
google.golang.org/protobuf/internal/impl.(*MessageInfo).makeReflectFuncs(0xc00015c000, 0x1985ae0, 0x17cb280, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xc0002a8630, 0xc0002a8660, 0xc0002a8690, ...)
	/Users/ruifengyun/go/pkg/mod/google.golang.org/protobuf@v1.25.0/internal/impl/message_reflect.go:36 +0x63
google.golang.org/protobuf/internal/impl.(*MessageInfo).initOnce(0xc00015c000)
	/Users/ruifengyun/go/pkg/mod/google.golang.org/protobuf@v1.25.0/internal/impl/message.go:90 +0x182
google.golang.org/protobuf/internal/impl.(*MessageInfo).init(0xc00015c000)
	/Users/ruifengyun/go/pkg/mod/google.golang.org/protobuf@v1.25.0/internal/impl/message.go:72 +0x3c
google.golang.org/protobuf/internal/impl.(*messageReflectWrapper).ProtoMethods(0xc00006c0e0, 0xc000155d28)
	/Users/ruifengyun/go/pkg/mod/google.golang.org/protobuf@v1.25.0/internal/impl/message_reflect_gen.go:150 +0x2f
google.golang.org/protobuf/proto.protoMethods(...)
	/Users/ruifengyun/go/pkg/mod/google.golang.org/protobuf@v1.25.0/proto/proto_methods.go:18
google.golang.org/protobuf/proto.MarshalOptions.marshal(0xc000000001, 0x0, 0x0, 0x0, 0x1980720, 0xc00006c0e0, 0xc00006c0e0, 0x1980720, 0xc00006c0e0, 0x1817ae0, ...)
	/Users/ruifengyun/go/pkg/mod/google.golang.org/protobuf@v1.25.0/proto/encode.go:143 +0x49
google.golang.org/protobuf/proto.MarshalOptions.MarshalAppend(0x1000001, 0x0, 0x0, 0x0, 0x1964f60, 0xc00006c0e0, 0x3a624a8, 0x1067ac2, 0x10557fc, 0x1069ef0, ...)
	/Users/ruifengyun/go/pkg/mod/google.golang.org/protobuf@v1.25.0/proto/encode.go:125 +0x98
github.com/golang/protobuf/proto.marshalAppend(0x0, 0x0, 0x0, 0x1971e00, 0x1ead560, 0x5fd03b00, 0xc0002eeef8, 0x1089bf6, 0x5fd03b34, 0x2789eed8, ...)
	/Users/ruifengyun/go/pkg/mod/github.com/golang/protobuf@v1.4.3/proto/wire.go:40 +0xbe
github.com/golang/protobuf/proto.Marshal(...)
	/Users/ruifengyun/go/pkg/mod/github.com/golang/protobuf@v1.4.3/proto/wire.go:23
github.com/smallnest/gosercomp.BenchmarkUnmarshalByGogoProtoBuf(0xc00019c540)
	/Users/ruifengyun/github/gosercomp/gosercomp_test.go:111 +0x61
testing.(*B).runN(0xc00019c540, 0x1)
	/usr/local/go/src/testing/benchmark.go:191 +0xe8
testing.(*B).run1.func1(0xc00019c540)
	/usr/local/go/src/testing/benchmark.go:231 +0x57
created by testing.(*B).run1
	/usr/local/go/src/testing/benchmark.go:224 +0x7d
exit status 2
FAIL	github.com/smallnest/gosercomp	12.964s
```

**Comment by smallnest** [comment]
thanks. I have fixed it.
